import { db } from '@/db';
import { disasterReports } from '@/db/schema';

async function main() {
    const sampleDisasterReports = [
        {
            title: 'Banjir Bandang & Longsor Tapanuli Selatan',
            description: 'Banjir bandang disertai longsor melanda Tapanuli Selatan. 79+ korban meninggal, 2.851 KK mengungsi. Jalan terputus, jembatan rusak, area terisolasi 3+ hari. Kayu gelondongan tersapu banjir.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '1.5400',
            longitude: '99.2500',
            locationName: 'Tapanuli Selatan',
            region: 'Tapanuli Selatan, Sumatera Utara',
            reporterName: 'Rizki Harahap',
            reporterContact: '+6281234567890',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Sumatera Utara',
            verifiedAt: new Date('2025-11-27T03:30:00Z').toISOString(),
            affectedResidents: 12000,
            urgentNeeds: 'makanan, air bersih, tenda darurat, obat-obatan, alat berat, jembatan darurat',
            photoUrl: null,
            createdAt: new Date('2025-11-27T02:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T02:00:00Z').toISOString(),
        },
        {
            title: 'Banjir Padang Sidempuan - Terisolasi',
            description: 'Kota Padang Sidempuan terisolasi berhari-hari akibat banjir. Akses darat terputus, bantuan via udara. Ribuan warga mengungsi.',
            category: 'flood',
            severity: 'Critical',
            latitude: '1.3800',
            longitude: '99.2700',
            locationName: 'Padang Sidempuan',
            region: 'Padang Sidempuan, Sumatera Utara',
            reporterName: 'Siti Nurhaliza Siregar',
            reporterContact: '+6281345678901',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'Basarnas Wilayah Sumut',
            verifiedAt: new Date('2025-11-27T04:15:00Z').toISOString(),
            affectedResidents: 8000,
            urgentNeeds: 'helikopter bantuan, makanan, air bersih, obat-obatan, tenda',
            photoUrl: null,
            createdAt: new Date('2025-11-27T02:45:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T02:45:00Z').toISOString(),
        },
        {
            title: 'Banjir Tapanuli Tengah - 1.902 Rumah Terendam',
            description: '1.902 rumah terendam di 9 kecamatan Tapanuli Tengah. Jembatan rusak, komunikasi terputus.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '1.8200',
            longitude: '98.9300',
            locationName: 'Pandan',
            region: 'Pandan, Tapanuli Tengah, Sumatera Utara',
            reporterName: 'Ahmad Daulay',
            reporterContact: '+6281456789012',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Tapanuli Tengah',
            verifiedAt: new Date('2025-11-27T05:00:00Z').toISOString(),
            affectedResidents: 9500,
            urgentNeeds: 'pompa air, makanan, selimut, tenda, perbaikan komunikasi',
            photoUrl: null,
            createdAt: new Date('2025-11-27T03:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T03:30:00Z').toISOString(),
        },
        {
            title: 'Banjir Humbang Hasundutan - 1.712 Mengungsi',
            description: '1.712 jiwa mengungsi di berbagai titik. Akses darat terputus, bantuan via udara sejak hari ke-3.',
            category: 'flood',
            severity: 'Critical',
            latitude: '2.2500',
            longitude: '98.6700',
            locationName: 'Doloksanggul',
            region: 'Doloksanggul, Humbang Hasundutan, Sumatera Utara',
            reporterName: 'Maria Situmorang',
            reporterContact: '+6281567890123',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'PMI Kabupaten Humbang Hasundutan',
            verifiedAt: new Date('2025-11-27T06:30:00Z').toISOString(),
            affectedResidents: 1712,
            urgentNeeds: 'bantuan udara, makanan, air bersih, selimut, tenda',
            photoUrl: null,
            createdAt: new Date('2025-11-27T05:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T05:00:00Z').toISOString(),
        },
        {
            title: 'Banjir Mandailing Natal - 1.378 Pengungsi',
            description: '1.378 jiwa mengungsi di 8 titik pengungsian. Area terdampak banjir parah.',
            category: 'flood',
            severity: 'Critical',
            latitude: '0.8300',
            longitude: '99.5400',
            locationName: 'Panyabungan',
            region: 'Panyabungan, Mandailing Natal, Sumatera Utara',
            reporterName: 'Budi Nasution',
            reporterContact: '+6281678901234',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Mandailing Natal',
            verifiedAt: new Date('2025-11-27T07:15:00Z').toISOString(),
            affectedResidents: 1378,
            urgentNeeds: 'makanan, air bersih, tenda, selimut, obat-obatan',
            photoUrl: null,
            createdAt: new Date('2025-11-27T05:45:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T05:45:00Z').toISOString(),
        },
        {
            title: 'Kota Sibolga Terisolasi Banjir',
            description: 'Kota Sibolga terisolasi berhari-hari, akses darat belum dibuka. Bantuan didistribusikan via udara.',
            category: 'flood',
            severity: 'Critical',
            latitude: '1.7400',
            longitude: '98.7800',
            locationName: 'Sibolga',
            region: 'Sibolga, Sumatera Utara',
            reporterName: 'Indra Lubis',
            reporterContact: '+6281789012345',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BNPB Regional Sumut',
            verifiedAt: new Date('2025-11-27T08:00:00Z').toISOString(),
            affectedResidents: 5000,
            urgentNeeds: 'bantuan udara, makanan, air bersih, BBM, genset',
            photoUrl: null,
            createdAt: new Date('2025-11-27T06:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T06:30:00Z').toISOString(),
        },
        {
            title: 'Jalan Utama Tapanuli Terputus',
            description: 'Jalan utama menuju Sibolga dan Padang Sidempuan terputus total. Jembatan rusak dan hanyut. Pembukaan akses masih berlangsung.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '1.7000',
            longitude: '99.0000',
            locationName: 'Tapanuli Tengah',
            region: 'Tapanuli Tengah, Sumatera Utara',
            reporterName: 'Dedi Purba',
            reporterContact: '+6281890123456',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'Dinas PUPR Sumut',
            verifiedAt: new Date('2025-11-28T03:30:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'alat berat, material jembatan darurat, pekerja konstruksi',
            photoUrl: null,
            createdAt: new Date('2025-11-28T02:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T02:00:00Z').toISOString(),
        },
        {
            title: 'Jembatan Rusak Tapanuli Selatan',
            description: 'Beberapa jembatan rusak dan hanyut. Akses evakuasi terganggu, butuh jembatan darurat.',
            category: 'flood',
            severity: 'Critical',
            latitude: '1.4500',
            longitude: '99.1800',
            locationName: 'Tapanuli Selatan',
            region: 'Tapanuli Selatan, Sumatera Utara',
            reporterName: 'Yusuf Manurung',
            reporterContact: '+6281901234567',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'BPBD Tapanuli Selatan',
            verifiedAt: new Date('2025-11-28T04:45:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'jembatan bailey, alat berat, material konstruksi',
            photoUrl: null,
            createdAt: new Date('2025-11-28T03:15:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T03:15:00Z').toISOString(),
        },
        {
            title: 'Kebutuhan Sembako Mendesak - Tapanuli',
            description: 'Kebutuhan sembako sangat mendesak. Insiden perebutan beras di gudang Bulog (1 korban meninggal). Butuh distribusi makanan segera untuk 570.000+ pengungsi.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '1.8000',
            longitude: '98.9500',
            locationName: 'Tapanuli Tengah',
            region: 'Tapanuli Tengah, Sumatera Utara',
            reporterName: 'Fitri Siahaan',
            reporterContact: '+6282012345678',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'BNPB Regional Sumut',
            verifiedAt: new Date('2025-11-29T04:00:00Z').toISOString(),
            affectedResidents: 570000,
            urgentNeeds: 'beras, mie instan, air mineral, makanan kaleng, distribusi terorganisir',
            photoUrl: null,
            createdAt: new Date('2025-11-29T02:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T02:30:00Z').toISOString(),
        },
        {
            title: 'Krisis Air Bersih - Area Terisolasi Sumut',
            description: 'Air bersih sangat kritis di area terisolasi. Sanitasi buruk, risiko penyakit menular tinggi.',
            category: 'flood',
            severity: 'Critical',
            latitude: '1.3800',
            longitude: '99.2700',
            locationName: 'Padang Sidempuan',
            region: 'Padang Sidempuan, Sumatera Utara',
            reporterName: 'Linda Pasaribu',
            reporterContact: '+6282123456789',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'PMI Wilayah Sumut',
            verifiedAt: new Date('2025-11-29T05:30:00Z').toISOString(),
            affectedResidents: 50000,
            urgentNeeds: 'air mineral galon, water purifier, tangki air, klorin',
            photoUrl: null,
            createdAt: new Date('2025-11-29T04:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T04:00:00Z').toISOString(),
        },
        {
            title: 'Butuh Obat-obatan & Tenaga Medis',
            description: 'Kebutuhan obat-obatan dan tenaga medis mendesak. Risiko infeksi dan penyakit menular tinggi di pengungsian.',
            category: 'flood',
            severity: 'Critical',
            latitude: '1.7400',
            longitude: '98.7800',
            locationName: 'Sibolga',
            region: 'Sibolga, Sumatera Utara',
            reporterName: 'Dr. Rahmat Simbolon',
            reporterContact: '+6282234567890',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'Dinkes Kota Sibolga',
            verifiedAt: new Date('2025-11-29T06:45:00Z').toISOString(),
            affectedResidents: 30000,
            urgentNeeds: 'obat diare, antibiotik, antiseptik, tenaga medis, masker',
            photoUrl: null,
            createdAt: new Date('2025-11-29T05:15:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T05:15:00Z').toISOString(),
        },
        {
            title: 'Banjir Bandang Agam - 118 Meninggal',
            description: 'Banjir bandang dan longsor menghancurkan Nagari Salareh Aia. 118 meninggal, 72 hilang, 6.300 mengungsi. Rumah terbenam lumpur, kayu gelondongan berserakan. Area terisolasi 3+ hari.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '-0.2300',
            longitude: '100.1500',
            locationName: 'Salareh Aia',
            region: 'Salareh Aia, Palembayan, Agam, Sumatera Barat',
            reporterName: 'Azwar Rahman',
            reporterContact: '+6282345678901',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kabupaten Agam',
            verifiedAt: new Date('2025-11-27T04:00:00Z').toISOString(),
            affectedResidents: 6300,
            urgentNeeds: 'tim SAR, excavator, makanan, air bersih, tenda darurat, body bag',
            photoUrl: null,
            createdAt: new Date('2025-11-27T02:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T02:30:00Z').toISOString(),
        },
        {
            title: 'Banjir Kota Padang - Batang Anai Meluap',
            description: 'Sungai Batang Anai meluap, kota Padang terendam. 33 meninggal, 32 hilang, 20.000+ mengungsi.',
            category: 'flood',
            severity: 'Critical',
            latitude: '-0.9471',
            longitude: '100.4172',
            locationName: 'Padang',
            region: 'Padang, Sumatera Barat',
            reporterName: 'Maya Zahara',
            reporterContact: '+6282456789012',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kota Padang',
            verifiedAt: new Date('2025-11-27T05:15:00Z').toISOString(),
            affectedResidents: 20000,
            urgentNeeds: 'evakuasi, makanan, air bersih, tenda, obat-obatan',
            photoUrl: null,
            createdAt: new Date('2025-11-27T03:45:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T03:45:00Z').toISOString(),
        },
        {
            title: 'Banjir Padang Panjang',
            description: 'Kota Padang Panjang terdampak banjir parah. Ribuan warga mengungsi, infrastruktur rusak.',
            category: 'flood',
            severity: 'Critical',
            latitude: '-0.4614',
            longitude: '100.4044',
            locationName: 'Padang Panjang',
            region: 'Padang Panjang, Sumatera Barat',
            reporterName: 'Syafrizal',
            reporterContact: '+6282567890123',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kota Padang Panjang',
            verifiedAt: new Date('2025-11-27T06:00:00Z').toISOString(),
            affectedResidents: 8000,
            urgentNeeds: 'makanan, air bersih, tenda, selimut',
            photoUrl: null,
            createdAt: new Date('2025-11-27T04:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T04:30:00Z').toISOString(),
        },
        {
            title: 'Banjir Padang Pariaman',
            description: 'Banjir melanda kawasan pesisir dan hulu Padang Pariaman. Akses jalan terganggu.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-0.6200',
            longitude: '100.1200',
            locationName: 'Parit Malintang',
            region: 'Parit Malintang, Padang Pariaman, Sumatera Barat',
            reporterName: 'Irwan Syahputra',
            reporterContact: '+6282678901234',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Padang Pariaman',
            verifiedAt: new Date('2025-11-27T07:30:00Z').toISOString(),
            affectedResidents: 3000,
            urgentNeeds: 'pompa air, makanan, air bersih',
            photoUrl: null,
            createdAt: new Date('2025-11-27T06:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T06:00:00Z').toISOString(),
        },
        {
            title: 'Banjir Pesisir Selatan',
            description: 'Kawasan pesisir Sumatera Barat terdampak banjir. Beberapa desa terendam.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-1.3500',
            longitude: '100.5700',
            locationName: 'Painan',
            region: 'Painan, Pesisir Selatan, Sumatera Barat',
            reporterName: 'Rina Marlina',
            reporterContact: '+6282789012345',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Pesisir Selatan',
            verifiedAt: new Date('2025-11-27T08:15:00Z').toISOString(),
            affectedResidents: 2000,
            urgentNeeds: 'perahu karet, makanan, air bersih',
            photoUrl: null,
            createdAt: new Date('2025-11-27T06:45:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T06:45:00Z').toISOString(),
        },
        {
            title: 'Banjir Kabupaten Solok',
            description: 'Area Solok terdampak banjir. Evakuasi warga dilakukan.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-0.7933',
            longitude: '100.6561',
            locationName: 'Arosuka',
            region: 'Arosuka, Solok, Sumatera Barat',
            reporterName: 'Andi Kurniawan',
            reporterContact: '+6282890123456',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kabupaten Solok',
            verifiedAt: new Date('2025-11-27T09:00:00Z').toISOString(),
            affectedResidents: 1500,
            urgentNeeds: 'evakuasi, makanan, tenda',
            photoUrl: null,
            createdAt: new Date('2025-11-27T07:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-27T07:30:00Z').toISOString(),
        },
        {
            title: 'Jembatan & Jalan Rusak Agam',
            description: 'Jembatan hancur di Agam, akses ke Nagari Salareh Aia terputus. Butuh jembatan darurat untuk evakuasi.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '-0.2500',
            longitude: '100.1300',
            locationName: 'Palembayan',
            region: 'Palembayan, Agam, Sumatera Barat',
            reporterName: 'Herman Junaidi',
            reporterContact: '+6282901234567',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'Dinas PUPR Kabupaten Agam',
            verifiedAt: new Date('2025-11-28T04:00:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'jembatan bailey, alat berat, material konstruksi',
            photoUrl: null,
            createdAt: new Date('2025-11-28T02:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T02:30:00Z').toISOString(),
        },
        {
            title: 'Kerusakan Infrastruktur Kota Padang',
            description: 'Jalan utama rusak, jembatan terganggu. Akses ke beberapa area masih terbatas.',
            category: 'flood',
            severity: 'Critical',
            latitude: '-0.9500',
            longitude: '100.4200',
            locationName: 'Padang',
            region: 'Padang, Sumatera Barat',
            reporterContact: '+6283012345678',
            reporterName: 'Fajar Pratama',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'Dinas PUPR Kota Padang',
            verifiedAt: new Date('2025-11-28T05:45:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'alat berat, aspal, material perbaikan jalan',
            photoUrl: null,
            createdAt: new Date('2025-11-28T04:15:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T04:15:00Z').toISOString(),
        },
        {
            title: 'Butuh Tenda & Shelter Darurat - Agam',
            description: '6.300 pengungsi Agam butuh tenda dan shelter darurat. Kondisi pengungsian overcrowded.',
            category: 'flood',
            severity: 'Emergency',
            latitude: '-0.2300',
            longitude: '100.1500',
            locationName: 'Palembayan',
            region: 'Palembayan, Agam, Sumatera Barat',
            reporterName: 'Riska Aulia',
            reporterContact: '+6283123456789',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'PMI Kabupaten Agam',
            verifiedAt: new Date('2025-11-29T04:30:00Z').toISOString(),
            affectedResidents: 6300,
            urgentNeeds: 'tenda besar, terpal, kasur lipat, selimut',
            photoUrl: null,
            createdAt: new Date('2025-11-29T03:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T03:00:00Z').toISOString(),
        },
        {
            title: 'Distribusi Logistik Belum Merata - Padang',
            description: 'Distribusi bantuan logistik belum merata. 20.000+ pengungsi butuh sembako, air bersih, dan perlengkapan kebersihan.',
            category: 'flood',
            severity: 'Critical',
            latitude: '-0.9471',
            longitude: '100.4172',
            locationName: 'Padang',
            region: 'Padang, Sumatera Barat',
            reporterName: 'Iwan Setiawan',
            reporterContact: '+6283234567890',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'BNPB Regional Sumbar',
            verifiedAt: new Date('2025-11-29T06:00:00Z').toISOString(),
            affectedResidents: 20000,
            urgentNeeds: 'beras, air mineral, sabun, pembalut, popok bayi',
            photoUrl: null,
            createdAt: new Date('2025-11-29T04:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T04:30:00Z').toISOString(),
        },
        {
            title: 'Banjir Bandang Pesisir Pidie Jaya',
            description: 'Banjir bandang melanda kawasan pesisir Pidie Jaya. Area terisolasi pascabanjir.',
            category: 'flood',
            severity: 'Alert',
            latitude: '5.1200',
            longitude: '96.2800',
            locationName: 'Meureudu',
            region: 'Meureudu, Pidie Jaya, Aceh',
            reporterName: 'Muhammad Hafiz',
            reporterContact: '+6283345678901',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Pidie Jaya',
            verifiedAt: new Date('2025-11-28T05:30:00Z').toISOString(),
            affectedResidents: 2500,
            urgentNeeds: 'perahu, makanan, air bersih, tenda',
            photoUrl: null,
            createdAt: new Date('2025-11-28T04:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T04:00:00Z').toISOString(),
        },
        {
            title: 'Butuh Akses Evakuasi - Pidie Jaya',
            description: 'Area terisolasi butuh akses darurat untuk evakuasi dan distribusi bantuan.',
            category: 'flood',
            severity: 'Critical',
            latitude: '5.1000',
            longitude: '96.2500',
            locationName: 'Pidie Jaya',
            region: 'Pidie Jaya, Aceh',
            reporterName: 'Siti Aisyah',
            reporterContact: '+6283456789012',
            status: 'Verified',
            reportType: 'needs',
            verifiedBy: 'Basarnas Wilayah Aceh',
            verifiedAt: new Date('2025-11-29T05:00:00Z').toISOString(),
            affectedResidents: 2500,
            urgentNeeds: 'helikopter, perahu motor, alat komunikasi',
            photoUrl: null,
            createdAt: new Date('2025-11-29T03:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-29T03:30:00Z').toISOString(),
        },
        {
            title: 'Banjir Kabupaten Bima - 294 Rumah Rusak',
            description: 'Hujan intensitas sedang-lebat disertai angin kencang. 294 KK terdampak, 294 rumah rusak. Tidak ada korban jiwa.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-8.4500',
            longitude: '118.7200',
            locationName: 'Desa Pandai',
            region: 'Desa Pandai, Woha, Bima, NTB',
            reporterName: 'Nurul Hidayah',
            reporterContact: '+6283567890123',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kabupaten Bima',
            verifiedAt: new Date('2025-11-28T06:15:00Z').toISOString(),
            affectedResidents: 1470,
            urgentNeeds: 'terpal, material perbaikan rumah, makanan',
            photoUrl: null,
            createdAt: new Date('2025-11-28T04:45:00Z').toISOString(),
            updatedAt: new Date('2025-11-28T04:45:00Z').toISOString(),
        },
        {
            title: 'Banjir Lombok Timur - 588 Rumah Rusak',
            description: 'Banjir melanda Kecamatan Pringgabaya dan Suele. 2.352 jiwa terdampak, 588 rumah rusak, 1 jembatan rusak. Air mulai surut.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-8.4000',
            longitude: '116.5500',
            locationName: 'Pringgabaya',
            region: 'Pringgabaya, Lombok Timur, NTB',
            reporterName: 'Agus Wijaya',
            reporterContact: '+6283678901234',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Lombok Timur',
            verifiedAt: new Date('2025-11-19T06:00:00Z').toISOString(),
            affectedResidents: 2352,
            urgentNeeds: 'pompa air, material perbaikan, makanan',
            photoUrl: null,
            createdAt: new Date('2025-11-19T04:30:00Z').toISOString(),
            updatedAt: new Date('2025-11-19T04:30:00Z').toISOString(),
        },
        {
            title: 'Jembatan Rusak Lombok Timur',
            description: '1 jembatan rusak akibat banjir. Akses antar desa terganggu.',
            category: 'flood',
            severity: 'Alert',
            latitude: '-8.4200',
            longitude: '116.5300',
            locationName: 'Suele',
            region: 'Suele, Lombok Timur, NTB',
            reporterName: 'Bayu Saputra',
            reporterContact: '+6283789012345',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'Dinas PUPR Lombok Timur',
            verifiedAt: new Date('2025-11-19T07:30:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'jembatan darurat, material konstruksi',
            photoUrl: null,
            createdAt: new Date('2025-11-19T06:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-19T06:00:00Z').toISOString(),
        },
        {
            title: 'Cuaca Ekstrem & Pohon Tumbang Bogor',
            description: 'Cuaca ekstrem dengan angin kencang di 4 kecamatan, 8 kelurahan. 14 rumah rusak tertimpa pohon tumbang. 49 jiwa terdampak.',
            category: 'storm',
            severity: 'Alert',
            latitude: '-6.5950',
            longitude: '106.8160',
            locationName: 'Bogor Tengah',
            region: 'Bogor Tengah, Kota Bogor, Jawa Barat',
            reporterName: 'Dian Permatasari',
            reporterContact: '+6283890123456',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BPBD Kota Bogor',
            verifiedAt: new Date('2025-11-18T05:45:00Z').toISOString(),
            affectedResidents: 49,
            urgentNeeds: 'chainsaw, terpal, material perbaikan rumah',
            photoUrl: null,
            createdAt: new Date('2025-11-18T04:15:00Z').toISOString(),
            updatedAt: new Date('2025-11-18T04:15:00Z').toISOString(),
        },
        {
            title: '14 Rumah Rusak Tertimpa Pohon',
            description: '14 rumah rusak tertimpa pohon tumbang akibat angin kencang.',
            category: 'storm',
            severity: 'Alert',
            latitude: '-6.6000',
            longitude: '106.8000',
            locationName: 'Bogor',
            region: 'Bogor, Jawa Barat',
            reporterName: 'Eko Prasetyo',
            reporterContact: '+6283901234567',
            status: 'Verified',
            reportType: 'infrastructure',
            verifiedBy: 'Dinas Perumahan Kota Bogor',
            verifiedAt: new Date('2025-11-18T06:30:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: 'material perbaikan, terpal, pekerja bangunan',
            photoUrl: null,
            createdAt: new Date('2025-11-18T05:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-18T05:00:00Z').toISOString(),
        },
        {
            title: 'Gempa M1.8 Selatan Bandung',
            description: 'Gempa tektonik dangkal magnitude 1.8 SR, kedalaman 86 km. Tidak berpotensi tsunami. Tidak ada kerusakan.',
            category: 'earthquake',
            severity: 'Normal',
            latitude: '-7.6800',
            longitude: '107.0400',
            locationName: 'Selatan Kota Bandung',
            region: 'Selatan Kota Bandung, Jawa Barat',
            reporterName: 'BMKG Bandung',
            reporterContact: '+6284012345678',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BMKG Stasiun Bandung',
            verifiedAt: new Date('2025-12-02T02:45:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: '',
            photoUrl: null,
            createdAt: new Date('2025-12-02T02:15:00Z').toISOString(),
            updatedAt: new Date('2025-12-02T02:15:00Z').toISOString(),
        },
        {
            title: 'Gempa M3.8 Enggano',
            description: 'Gempa magnitude 3.8 SR, kedalaman 14 km. Tidak berpotensi tsunami. Dirasakan skala MMI II-III (lemah). Tidak ada kerusakan.',
            category: 'earthquake',
            severity: 'Normal',
            latitude: '-5.1100',
            longitude: '102.3800',
            locationName: 'Timur Laut Enggano',
            region: 'Timur Laut Enggano, Bengkulu',
            reporterName: 'BMKG Bengkulu',
            reporterContact: '+6284123456789',
            status: 'Verified',
            reportType: 'disaster',
            verifiedBy: 'BMKG Stasiun Bengkulu',
            verifiedAt: new Date('2025-11-30T04:30:00Z').toISOString(),
            affectedResidents: 0,
            urgentNeeds: '',
            photoUrl: null,
            createdAt: new Date('2025-11-30T04:00:00Z').toISOString(),
            updatedAt: new Date('2025-11-30T04:00:00Z').toISOString(),
        },
    ];

    await db.insert(disasterReports).values(sampleDisasterReports);

    console.log('✅ Disaster reports seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});